name: yo

on: [pull_request, whatever, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'whut did u just do''rake it up'
        pr-message: 'thismuhritehurdonfkdwitmyshit'' whut'
